### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by la32094uf** [reverendj1/kodi-couch-ripper#2]
It leads to an  error within Kodi. Hope you can squeeze down this problem?

Macmini (20:20):
19:51:11 T:4515958784  NOTICE: Thread LanguageInvoker start, auto delete: false
19:51:11 T:4515958784  NOTICE: -->Python Interpreter Initialized<--
19:51:13 T:4515958784  NOTICE: script.couch_ripper-0.1.5 : Beginning Rip. Command: nice -n -19  "/Applications/MakeMKV.app/Contents/MacOS/makemkvcon" mkv --decrypt disc:0 all --minlength=2700 "/Users/macmini/Desktop/Temp/"
19:51:13 T:4515958784   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'check_output'
                                            Traceback (most recent call last):
                                              File "/Users/macmini/Library/Application Support/Kodi/addons/kodi-couch-ripper-master/default.py", line 607, in <module>
                                                sys.exit(main(sys.argv))
                                              File "/Users/macmini/Library/Application Support/Kodi/addons/kodi-couch-ripper-master/default.py", line 49, in main
                                                ripoutput = subprocess.check_output(
                                            AttributeError: 'module' object has no attribute 'check_output'
                                            -->End of Python script error report<--
19:51:19 T:4515958784  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by reverendj1** [comment]
I think that makes you my first Mac user. I see what the issue is, apparently Kodi for Mac uses an old version of Python. I should be able to code around this though. Hopefully it won't cause another issue further down in the plugin. I'll look into it. Thanks for letting me know.

**Comment by jknight2014** [comment]
Are you sure kodi for mac is intentionally using an older python or could realbase just need to upgrade?

**Comment by reverendj1** [comment]
Installing Python 2.7 system-wide may fix the issue, but it looks like it's standard for Kodi to ship with 2.6 on Macs. http://forum.kodi.tv/showthread.php?tid=216598 Windows ships with 2.7 and Linux uses the OS's version (typically 2.7) http://forum.kodi.tv/showthread.php?tid=218112

**Comment by jknight2014** [comment]
Very good, I was not sure if it shipped with a different version than the windows version.

**Comment by la32094uf** [comment]
i installed python 2.7.9 but still no luck... :(

**Comment by reverendj1** [comment]
@realbase go ahead and reinstall and try again. I worked around the missing feature I'm using in Python 2.7. Hopefully that was the only feature not in 2.6. Let me know if it works or not.

**Comment by la32094uf** [comment]
Yes, it works! Ripped a few DVD's now. Great. Finally I can get rid of my whole DVD-collection :-D
