### ISSUE TITLE
all settings are reported as invalid when launched

### ISSUE THREAD

**Issue by eleith** [reverendj1/kodi-couch-ripper#3]
running in krypton, perhaps add-on doesn't work with krptyon?

did krypton update how settings are pulled in?

**Comment by reverendj1** [comment]
It works fine in Krypton. There is some setup required. Did you configure the defaults and any presets?

**Comment by eleith** [comment]
yup.

i noticed something strange.

i get "invalid CPU priority" but when i update the settings line to

`<settings type="string" id="defaultniceness">Low</setting>`

i no longer get an error and the invalid errors move on to the next setting.

originally, the setting was as such

`<settings type="string" id="defaultniceness" value="Low"/>`

i'm still poking around, maybe something is different with my environment.

**Comment by eleith** [comment]
scratch that. i was just reading the notification banner wrong. in the logs, it still says invalid. 

is their a way to turn up the logging so i can further debug?

**Comment by reverendj1** [comment]
There's no debug logging setting specific to Couch Ripper, but you can enable debug logging for Kodi as a whole. http://kodi.wiki/view/Log_file/Advanced#Enable_debugging If you want to enable that, close Kodi, open it back up, immediately try to do whatever it is that's causing the error, and copy and paste the log here, I might be able to help.

What OS are you using? What are you doing when it errors out?

**Comment by eleith** [comment]
thanks. appreciate the pointers.

i'm using linux. i get the errors when i launch the default profile on couch ripper.

my two guess is that it either doesn't grab the right settings file or it does, but it reads it incorrectly.

will poke around more when i get a chance.

**Comment by reverendj1** [comment]
What distro? I am using Ubuntu 16.04. If you get me that log I can probably figure it out. I'll wipe my config later tonight and see if I get any errors with the defaults. I haven't built a config from scratch on Krypton, so there might be something going on there.

**Comment by eleith** [comment]
16.10, mainline ubuntu.

ok, i enabled advanced debugging... and now it works.

not sure if it is about restarting kodi, or the advanced logging or what not. will need more time, but clearly it's an environment problem or some set of steps that i haven't figured out.

oh well. i'll report back if i can reproduce. happy to have it working though.

amazing addon, thanks for building and sharing it! (and for being so responsive).

i would still recommend building a config from scratch to see if you can reproduce (i'll try as well). 

thanks again!

**Comment by reverendj1** [comment]
Sweet. Glad it's working out for you now. Thanks for taking the time to report a bug instead of just ignoring it. I don't really get much feedback on this plugin, so I'm not really sure how much it's used. I'll wipe my config later and see if I notice any weirdness. FYI, I am working on a new version I hope to release in the next few days. It just fixes an issue where when you select Foreign language, it transcodes all the audio in 2 channel, instead of 5.1. It probably seems like a dead project because of the lack of commits, but it's just not had many issues.

**Comment by eleith** [comment]
yup, many of these tools are stable, so it makes sense that this script doesn't need much updating (unless kodi changes up something).

i have my own set of scripts, but i came across this in the forums and i like the idea of a more integrated approach. will try out the update when it is released and report back if i find problems.
